# See: https://dart.dev/tools/pub/pubspec

name: HumanLifeGame
description: HumanLife Game
documentation: https://sensuikan1973.github.io/HumanLifeGame/
repository: https://github.com/sensuikan1973/HumanLifeGame
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.9.0-21.2.beta <3.0.0"
  flutter: ">= 1.20.0-7.2.pre <2.0.0" # See: https://flutter.dev/docs/development/tools/sdk/releases

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  email_validator: ^1.0.5
  firebase_auth: ^0.16.1
  cloud_firestore: 0.13.6 # 固定な理由は https://github.com/sensuikan1973/HumanLifeGame/pull/237#issuecomment-663775596
  firestore_ref: ^0.8.19+1
  flutter_dotenv: ^2.1.0
  freezed_annotation: ^0.11.0
  provider: ^4.3.1
  shared_preferences: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  cloud_firestore_mocks: ^0.4.5
  dartman_sensuikan1973:
    git:
      url: https://github.com/sensuikan1973/dartman_sensuikan1973
      ref: 1.2.0
  freezed: ^0.11.4
  intl_translation: ^0.17.10
  json_serializable: ^3.3.0
  mockito: ^4.1.1
  uuid: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - config/.env
    # https://sozai-good.com/illust/free-background/cute/29847
    - images/play_view_background.jpg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages