name: Flutter_Analyzer

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  flutter_analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      # See: https://github.com/subosito/flutter-action/issues/39
      #     でもなんかなおってないぽなので、channel + upgrade を入れている
      # FIXME: いつか消す
      - run: flutter channel beta
      - run: flutter upgrade

      - run: flutter pub get
      - run: flutter analyze
