name: Flutter_Web_Deploy

on:
  push:
    branches:
      - master
      - firebase_deploy_status

jobs:
  flutter_build_web:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Workaround for https://github.com/subosito/flutter-action/issues/39
        run: flutter channel beta && flutter upgrade
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter packages pub run build_runner build
      - run: flutter build web
      - uses: actions/upload-artifact@master
        with:
          name: human_life_game_web
          path: build/web

  firebase_hosting_deploy:
    needs: flutter_build_web
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@master
        with:
          name: human_life_game_web
          path: build/web

      - name: start deploy
        uses: chrnorm/deployment-status@releases/v1
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_url: https://human-life-game-dev.web.app/
          environemnt: dev

      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting -P dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_TOKEN }}

      - name: update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_url: https://human-life-game-dev.web.app/
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      - name: update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_url: https://human-life-game-dev.web.app/
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
