name: Flutter_Test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  flutter_widget_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter channel beta # tomporary command. Error at:https://github.com/sensuikan1973/HumanLifeGame/pull/84/checks?check_run_id=658350302#step:4:38
      - run: flutter upgrade # tomporary command
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter test --no-test-assets --coverage --coverage-path=~/coverage/lcov.info
      - uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ~/coverage/lcov.info
