name: Flutter_Analyzer

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  flutter_analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Workaround for https://github.com/subosito/flutter-action/issues/39
        run: flutter channel beta && flutter upgrade
      - run: flutter pub get
      - run: flutter packages pub run build_runner build
      - run: cp config/.env.sample config/.env
      - run: flutter analyze
