name: Flutter_Build_Web

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  flutter_build_web:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter channel beta # tomporary command. Error at:https://github.com/sensuikan1973/HumanLifeGame/runs/652208459?check_suite_focus=true#step:7:7
      - run: flutter upgrade # tomporary command
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web
