name: Upload_Dart_Docs

on:
  push:
    branches:
      - master

jobs:
  upload_dart_docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Workaround for https://github.com/subosito/flutter-action/issues/39
        run: flutter channel beta && flutter upgrade
      - run: .github/scripts/setup_flutter_web.sh
      - name: generate dart docs
        run: FLUTTER_ROOT=$FLUTTER_HOME dartdoc --output docs/
      - name: upload
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
